export enum NotificationType {
  RIDE_ACCEPTED = 'RIDE_ACCEPTED',
  RIDE_REJECTED = 'RIDE_REJECTED',
  RIDE_ASSIGNED = 'RIDE_ASSIGNED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  RIDE_CANCELLED = 'RIDE_CANCELLED',
  RIDE_REMINDER = 'RIDE_REMINDER',
  PANIC_ALERT = 'PANIC_ALERT',
  PASSENGER_LINKED = 'PASSENGER_LINKED',
  PROFILE_CHANGE_APPROVED = 'PROFILE_CHANGE_APPROVED',
  PROFILE_CHANGE_REJECTED = 'PROFILE_CHANGE_REJECTED',
  TIME_FOR_A_RIDE = 'TIME_FOR_A_RIDE',
  RIDE_STARTED = 'RIDE_STARTED',
}
